language: java
jdk: openjdk8
 
script:
- mvn package

after_success:
  - docker build -t wondee/finance-application .

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
