language: java
jdk: openjdk8
 
before_script: cd finance-application

script:
- mvn package

after_success:
  - docker build -t wondee/finance-application .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
