POST http://localhost:8082/api/costs/halfyearly
content-type: application/json

{
  "id": null,
  "name": "Sportverein",
  "amount": -10,
  "from": null,
  "to": null,
  "dueMonth": 5
}
###
POST http://localhost:8082/api/specialcosts
content-type: application/json

{
  "id": null,
  "name": "Urlaub",
  "amount": -2000,
  "dueDate": {
    "year": 2021,
    "month": 12
  }
}
###
GET http://localhost:8082/api/user
#X-MS-CLIENT-PRINCIPAL-ID: testeeWithout@gmail.com
###
PUT http://localhost:8082/api/user
###
GET http://localhost:8082/api/costs
###
DELETE http://localhost:8082/api/costs/4
###
GET http://localhost:8082/api/specialcosts
###
DELETE http://localhost:8082/api/specialcosts/2
###
GET http://localhost:8082/api/overview/all
