version: '2'
services:
  nginx:
    image: wondee/finance-frontproxy
    restart: always
    ports:
      - 80:80
      - 443:443
    
  web:
    image: wondee/finance-application
    environment:
     - SPRING_DATA_MONGODB_URI=mongodb://mongo/financeapp

  mongo-seed: 
    links: 
      - mongo 
    image: wondee/finance-mongo-seed
    environment:
      WAIT_HOSTS: mongo:27017

  mongo:
    image: mongo