version: '2'

services:
  
  nginx:
    image: wondee/finance-frontproxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt
    networks:
      - app
  
  web:
    image: wondee/finance-application
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo/financeapp
    networks:
      - app

  mongo:
    image: mongo
    volumes: 
      - mongodata:/data/db
    networks:
      - app
      - mongo_import
      
volumes:
  mongodata:          
    driver: local
  letsencrypt_certs:  
    driver: local
  letsencrypt_www:    
    driver: local

networks:
  app:          
    driver: bridge
  mongo_import: 
    driver: bridge
